apiVersion: v1
kind: Pod
metadata:
  name: pvc-loader
  namespace: argo
spec:
  containers:
  - name: loader
    image: alpine
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: protogcn-pvc