# 학습 workflow 정의
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: protogcn-run-
spec:
  entrypoint: run
  imagePullSecrets:        # 전체 템플릿에 적용
    - name: dockerhub-secret
  arguments:
    parameters:
    - name: user

  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: protogcn-pvc

  templates:
  - name: run
    dag:
      tasks:
      - name: train
        template: train-one
        arguments:
          parameters:
            - name: pkl_path
              value: "/run/desktop/mnt/host/wsl/protogcn/uploads/{{workflow.parameters.user}}/*.pkl"  # data 추가
            - name: output_dir
              value: "/run/desktop/mnt/host/wsl/protogcn/results/{{workflow.parameters.user}}"

  - name: train-one
    inputs:
      parameters:
      - name: pkl_path
      - name: output_dir
    container:
      image: bianbbc87/csdc-proto-gcn:latest
      command: ["python", "auto_protogcn.py"]
      imagePullPolicy: IfNotPresent
      env:
      - name: DATASET_PKL
        value: "{{inputs.parameters.pkl_path}}"
      - name: RUNS_ROOT
        value: "{{inputs.parameters.output_dir}}"
      volumeMounts:
      - name: shared-volume
        mountPath: /run/desktop/mnt/host/wsl/protogcn

  # 3. CSV 병합
  - name: merge-results
    container:
      image: bianbbc87/csdc-protogcn-merge:latest
      command: ["python", "/app/index.py"]
      volumeMounts:
      - name: shared-volume
        mountPath: /run/desktop/mnt/host/wsl/protogcn
